//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortableClickonce {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PCResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PCResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortableClickonce.PCResource", typeof(PCResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;url indiquée ne contient pas d&apos;application Clickonce.
        /// </summary>
        internal static string BadClickonceUrlMessage {
            get {
                return ResourceManager.GetString("BadClickonceUrlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le repertoire d&apos;installation doit etre renseigné et valide.
        /// </summary>
        internal static string BadInstallationFolderMessage {
            get {
                return ResourceManager.GetString("BadInstallationFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;url de téléchargemnet clickonce doit etre renseignée et valide.
        /// </summary>
        internal static string BadSettingsUrlMessage {
            get {
                return ResourceManager.GetString("BadSettingsUrlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir....
        /// </summary>
        internal static string ChooseDirectoryButtonText {
            get {
                return ResourceManager.GetString("ChooseDirectoryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse du logiciel (exemple : http://www.clickonce.net/demo.application) :.
        /// </summary>
        internal static string ClickonceUrlLabelText {
            get {
                return ResourceManager.GetString("ClickonceUrlLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        internal static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier de deploiement chargé.
        /// </summary>
        internal static string DeployFileLoadedMessage {
            get {
                return ResourceManager.GetString("DeployFileLoadedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléchargement déjà en cours.
        /// </summary>
        internal static string DownloadAlreadyInProgressMessage {
            get {
                return ResourceManager.GetString("DownloadAlreadyInProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charger....
        /// </summary>
        internal static string DownloadButtonText {
            get {
                return ResourceManager.GetString("DownloadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status code: {0}.
        /// </summary>
        internal static string FileDownloadErrorMessage {
            get {
                return ResourceManager.GetString("FileDownloadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement du fichier : {0}.
        /// </summary>
        internal static string FileDownloadMessage {
            get {
                return ResourceManager.GetString("FileDownloadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lancer.
        /// </summary>
        internal static string LaunchButtongText {
            get {
                return ResourceManager.GetString("LaunchButtongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répertoire d&apos;installation :.
        /// </summary>
        internal static string LocalInstallationFolderLabelText {
            get {
                return ResourceManager.GetString("LocalInstallationFolderLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostique :.
        /// </summary>
        internal static string LogLabelText {
            get {
                return ResourceManager.GetString("LogLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier Manifest Chargé.
        /// </summary>
        internal static string ManifestFileLoadedMessage {
            get {
                return ResourceManager.GetString("ManifestFileLoadedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur Portable Clickonce.
        /// </summary>
        internal static string MsgBoxErrorTitle {
            get {
                return ResourceManager.GetString("MsgBoxErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Clickonce Attention !.
        /// </summary>
        internal static string MsgBoxWarningTitle {
            get {
                return ResourceManager.GetString("MsgBoxWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La configuration ne doit pas etre vide.
        /// </summary>
        internal static string SettingsDoesNotBeNullMessage {
            get {
                return ResourceManager.GetString("SettingsDoesNotBeNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Début du chargement.
        /// </summary>
        internal static string StartDownloadLogMessage {
            get {
                return ResourceManager.GetString("StartDownloadLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Début du chargement des fichiers nécéssaires.
        /// </summary>
        internal static string StartingDownloadMessage {
            get {
                return ResourceManager.GetString("StartingDownloadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement de {0} fichier(s).
        /// </summary>
        internal static string TotalFileCountMessage {
            get {
                return ResourceManager.GetString("TotalFileCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le numéro de version en cours est impossible à determiner.
        /// </summary>
        internal static string UnknownVersionMessage {
            get {
                return ResourceManager.GetString("UnknownVersionMessage", resourceCulture);
            }
        }
    }
}
